// Default `generalSettings` values (the shape of `conf/conf.json`); the fallback
// every field validator and the settings store starts from.

import type { GeneralSettings } from "$lib/types/clipboard";
import { DARK_THEME_COLORS } from "$lib/types/clipboard";

export const DEFAULT_GENERAL_SETTINGS: GeneralSettings = {
  language: "system",
  fontSizes: { base: 14, secondary: 11, tiny: 10, cardTitle: 13, cardPreview: 11 },
  display: { showSecondaryText: true, maxTextLines: 3, pageSize: 100, searchPageSize: 100 },
  windowTransparency: 95,
  windowEffect: "off",
  windowOpacityAffectsText: false,
  cardPaddingTop: 3,
  cardPaddingBottom: 3,
  cardGap: 2,
  cardTextHeight: 42,
  cardTallTextHeight: 42,
  cardImageHeight: 80,
  searchHeight: 30,
  searchFontSize: 20,
  cardBorderRadius: 5,
  pinCopiedToTop: true,
  useRecycleBin: true,
  pasteCleaningEnabled: false,
  doubleClickPaste: true,
  showToastNotifications: true,
  rememberWindowPosition: false,
  alwaysOnTop: false,
  useSystemTitleBar: false,
  theme: "dark",
  customCssEnabled: false,
  customCss: "",
  themeColors: { ...DARK_THEME_COLORS },
  customPresets: [],
  activePresetId: undefined,
  imageFullscreenMode: "overlay",
  viewerBackdropOpacity: 92,
  searchSuggestionMode: "off",
  floatPanelPosition: "bottomRight",
  floatPanelLeftClick: "copy",
  floatPanelRightClick: "none",
  floatPanelMiddleClick: "none",
  searchHistoryEnabled: false,
  searchPlaceholder: "",
  cardActionsDisplay: "hover",
  quickCopyBadgeAlwaysVisible: true,
  showSettingsCloseButton: true,
  detailDisplayMode: "overlay",
  groupDisplayMode: "iconText",
  searchSortRules: [{ field: "lastUsedAt", direction: "desc" }],
  savedSearches: [],
  pageSizeLimit: 500,
  searchPageSizeLimit: 500,
  maxTextCaptureBytes: 500000,
  searchCacheSize: 500,
  searchCacheEviction: "fifo",
  searchIndexSyncMode: "lazy",
  updateSource: "gitcode",
  colorIcons: false,
  iconColors: {},
  loadTolerance: 100,
  logLevel: "info",
};
